# Generated by Django 2.2.3 on 2019-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHDPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField()),
                ('isSmoker', models.BooleanField()),
                ('onBPM', models.BooleanField()),
                ('stroke', models.BooleanField()),
                ('hypertension', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('eduation', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('cigs', models.IntegerField()),
                ('cholesterol', models.FloatField()),
                ('sysBP', models.FloatField()),
                ('diaBP', models.FloatField()),
                ('BMI', models.FloatField()),
                ('heartRate', models.FloatField()),
                ('glucose', models.FloatField()),
            ],
        ),
    ]
