# Generated by Django 2.2.3 on 2019-08-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chdpredictions',
            old_name='eduation',
            new_name='education',
        ),
    ]
