# Generated by Django 2.2.3 on 2019-08-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190805_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='chdpredictions',
            name='hasCHD',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
